import { FormEvent, useState } from "react";
import { Download, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api } from "../lib/api";

export default function Settings() {
  const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "", confirmation: "" });
  const [saving, setSaving] = useState(false);
  async function changePassword(event: FormEvent) { event.preventDefault(); if (passwords.newPassword !== passwords.confirmation) { toast.error("A confirmação não confere."); return; } setSaving(true); try { await api.changePassword({ currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }); toast.success("Senha alterada. As outras sessões foram encerradas."); setPasswords({ currentPassword: "", newPassword: "", confirmation: "" }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível alterar sua senha."); } finally { setSaving(false); } }
  async function exportData() { try { const blob = await api.exportData(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `meu-dinheiro-no-controle-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); toast.success("Seus dados foram exportados."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível exportar seus dados."); } }
  return <div className="page-stack page-enter"><div className="section-heading"><div><div className="eyebrow">segurança e autonomia</div><h1>Minha conta</h1></div><p className="section-detail">Seus dados são seus. Mantenha o acesso protegido e leve uma cópia quando quiser.</p></div><div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">acesso protegido</span><h2><KeyRound size={17} /> Trocar senha</h2></div><LockKeyhole size={18} className="sparkle-icon" /></div><form className="compact-form" onSubmit={changePassword}><label>senha atual<input required type="password" minLength={8} value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /></label><label>nova senha<input required type="password" minLength={8} value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} /></label><label>confirmar nova senha<input required type="password" minLength={8} value={passwords.confirmation} onChange={(event) => setPasswords({ ...passwords, confirmation: event.target.value })} /></label><button className="primary-button" type="submit" disabled={saving}><ShieldCheck size={16} /> {saving ? "salvando..." : "alterar senha"}</button></form><p className="settings-note">Ao trocar sua senha, o sistema encerra as outras sessões para proteger sua conta.</p></section><section className="panel settings-panel settings-export"><div className="panel-heading"><div><span className="eyebrow">portabilidade</span><h2><Download size={17} /> Seus dados</h2></div></div><p>Baixe uma cópia em JSON com seu perfil, lançamentos, recorrências, compras, dívidas, metas e planejamento. O arquivo é gerado apenas para sua sessão autenticada.</p><button className="secondary-admin-button" type="button" onClick={exportData}><Download size={16} /> exportar meus dados</button><div className="settings-privacy"><ShieldCheck size={17} /><span>O sistema não exibe suas informações financeiras para outros usuários. Cada consulta é filtrada pelo seu identificador de sessão.</span></div></section></div></div>;
}
